//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace display.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guideline
    {
        public string customerId { get; set; }
        public string guidelines { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
